"""change comps type

Revision ID: 04511441de8e
Revises: 9b29a9d2f4f1
Create Date: 2025-05-14 18:04:39.244558

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04511441de8e"
down_revision: str | None = "9b29a9d2f4f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("resumes", "compensation", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("resumes", "compensation", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
