"""empty message

Revision ID: 7cf07797f5c0
Create Date: 2025-05-13 20:52:22.009628

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7cf07797f5c0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "resumes", "title", existing_type=sa.VARCHAR(length=256), type_=sa.String(length=200), nullable=False
    )
    op.alter_column(
        "resumes", "workload", existing_type=postgresql.ENUM("parttime", "fulltime", name="workload"), nullable=False
    )
    op.alter_column("resumes", "worker_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "resumes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
    )
    op.alter_column(
        "resumes",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
    )
    op.create_index("title_index", "resumes", ["title"], unique=False)
    op.alter_column("vacancies", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.add_column("vacancies_replies", sa.Column("cover_letter", sa.String(), nullable=True))
    op.alter_column("workers", "username", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("workers", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("vacancies_replies", "cover_letter")
    op.alter_column("vacancies", "title", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index("title_index", table_name="resumes")
    op.alter_column(
        "resumes",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
    )
    op.alter_column(
        "resumes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
    )
    op.alter_column("resumes", "worker_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "resumes", "workload", existing_type=postgresql.ENUM("parttime", "fulltime", name="workload"), nullable=True
    )
    op.alter_column(
        "resumes", "title", existing_type=sa.String(length=200), type_=sa.VARCHAR(length=256), nullable=True
    )
    # ### end Alembic commands ###
