"""migrations_2

Revision ID: 9b29a9d2f4f1
Revises: 7cf07797f5c0
Create Date: 2025-05-14 17:21:01.657745

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9b29a9d2f4f1"
down_revision: str | None = "7cf07797f5c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("resumes", "compensation", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "resumes", "created_at", existing_type=postgresql.TIMESTAMP(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "resumes", "updated_at", existing_type=postgresql.TIMESTAMP(), server_default=None, existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "resumes",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("timezone('utc'::text, now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "resumes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("timezone('utc'::text, now())"),
        existing_nullable=False,
    )
    op.alter_column("resumes", "compensation", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
